"""Pre-commit hook configuration generator."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path


class PrecommitGenerator:
    """Generates a ``.pre-commit-config.yaml`` for dev-stats.

    Produces a complete pre-commit configuration file that runs dev-stats
    as a local hook with configurable analysis options.
    """

    def generate(
        self,
        *,
        languages: tuple[str, ...] | None = None,
        exclude_patterns: tuple[str, ...] | None = None,
        quiet: bool = True,
    ) -> str:
        """Generate the pre-commit config YAML.

        Args:
            languages: Optional language filter (e.g. ``('python', 'java')``).
            exclude_patterns: Glob patterns to exclude from analysis.
            quiet: Whether to run in quiet mode.

        Returns:
            Complete YAML string for ``.pre-commit-config.yaml``.
        """
        entry_parts = ["dev-stats", "analyse", ".", "--fail-on-violations"]
        if quiet:
            entry_parts.append("--quiet")
        if languages:
            for lang in languages:
                entry_parts.extend(["--lang", lang])
        if exclude_patterns:
            for pat in exclude_patterns:
                entry_parts.extend(["--exclude", pat])

        entry = " ".join(entry_parts)

        return f"""\
# dev-stats pre-commit configuration
# Generated by: dev-stats init-hooks
repos:
  - repo: local
    hooks:
      - id: dev-stats
        name: dev-stats quality check
        entry: {entry}
        language: system
        types_or: [python, java, javascript, typescript, c, cpp, csharp, go]
        pass_filenames: false
        always_run: true
"""

    def write(self, output_dir: Path, **kwargs: object) -> Path:
        """Write the config to ``.pre-commit-config.yaml``.

        Args:
            output_dir: Directory to write into.
            **kwargs: Forwarded to :meth:`generate`.

        Returns:
            Path to the generated file.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        out_path = output_dir / ".pre-commit-config.yaml"
        content = self.generate(**kwargs)  # type: ignore[arg-type]
        out_path.write_text(content, encoding="utf-8")
        return out_path
